language: "perl"

perl:
  - "5.22"
  - "5.14"

services:

env:

sudo: false

addons:
    apt:
        packages:
        - unzip

before_install:
    - git clone --branch 0.3.0 --depth=1 https://github.com/dpryan79/libBigWig.git
    - cd libBigWig
    - make prefix=$HOME/libBigWig install
    - cd ..

install:
    # manually install items from cpanfile so we can skip BioPerl
    - cpanm --installdeps --with-all-features .
    - perl Build.PL --libbigwig=~/libBigWig

script: "./Build test"
